language: node_js
sudo: false
node_js:
  - 11
install:
  - npm install
  - npm install -D terser@3.14.1
script:
  - npm run build
  - npm run lint
deploy:
  provider: pages
  local-dir: build
  committer-from-gh: true
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master