name: build

on: [push, pull_request]

jobs:
  build:
    # Let's implement different jobs for Windows and Linux at some point, especially for packaging scripts
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Display Node.js and npm informations
        run: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

      - name: Install dependencies
        run: npm ci

      - name: Rebuild native modules
        run: npm run modules:rebuild

      - name: 'Test: formatting'
        run: 'npm run test:formatting'

      - name: 'Test: TS/JS linting'
        run: 'npm run test:lint'

      - name: 'Test: CSS linting'
        run: 'npm run test:css'

      - name: Build application
        run: npm run build
